apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp
  name: webapp
spec:
  containers:
  - image: kodekloud/webapp-color
    name: webapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
